### ISSUE TITLE
bug show_results

### ISSUE THREAD

**Issue by iceriver97** [NVlabs/VoxFormer#12]
```
Traceback (most recent call last):
  File "./tools/test.py", line 263, in <module>
    main()
  File "./tools/test.py", line 228, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/Dataset/weiqian/mmdetection3d/mmdet3d/apis/test.py", line 53, in single_gpu_test
    out_dir=out_dir,
  File "/home/Dataset/weiqian/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 466, in show_results
    if isinstance(data['points'][0], DC):
KeyError: 'points'
```

**Comment by YoushaaMurhij** [comment]
I met the same error when I tried to launch no dist. test script.
`python $(dirname "$0")/test.py $CONFIG $CHECKPOINT --eval bbox --show`

**Comment by a2801603396** [comment]
I met the same error. Counld you tell me how to solved it?

**Comment by a2801603396** [comment]
If I don't add - show during testing, I won't report this error. But I also report this error during training. This error will be reported when training 1 epochs validation.

**Comment by RoboticsYimingLi** [comment]
Please use dist mode. Thanks!

**Comment by h0n1** [comment]
> Please use dist mode. Thanks!

It seems that show mode is not supported when use non dist mode 

if not distributed:
        # assert False
        model = MMDataParallel(model, device_ids=[0])
        outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
    else:
        model = MMDistributedDataParallel(
            model.cuda(),
            device_ids=[torch.cuda.current_device()],
            broadcast_buffers=False)
        outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
                                        args.gpu_collect)
