### ISSUE TITLE
Visualizing result from stage 2

### ISSUE THREAD

**Issue by Shiyao-Xu** [NVlabs/VoxFormer#54]
For whom might also be interested in:

If you have the same question as I regarding visualization method, here is my solution. 

First, run the eval script and make sure to save the output as .pkl file.

Then, load this .pkl file(needs big memory), and you can see that the data is in the shape of 815 x (1x256x256x32). 

Next, do not hesitate to split the data into 815 pieces, each of which is 1 x 256 x 256 x 32. Save each piece with the name 000000.label ~ xxxxxx.label (6 digits).

And then, install semantic-kitti-api.

Prepare kitti dataset, save the corresponding data as semantic-kitti-api asks you to do, and copy your just created label in the same path, just ignore the label from the official kitti dataset. 

Finally, use the command copied from "Voxel Grids for Semantic Scene Completion" , and you will get your result.

**Comment by cc1oud** [comment]
Hi， I want to know how to save the output as .pkl file, I only has the .pth file.

**Comment by Shiyao-Xu** [comment]
> Hi， I want to know how to save the output as .pkl file, I only has the .pth file.

you could change the extension from .pth to .pkl, there is no big difference, only different ways when saving data.

**Comment by Shiyao-Xu** [comment]
> > Hi， I want to know how to save the output as .pkl file, I only has the .pth file.
> 
> you could change the extension from .pth to .pkl, there is no big difference, only different ways when saving data.

ps: change the extension in the code.

**Comment by cc1oud** [comment]
> > > Hi， I want to know how to save the output as .pkl file, I only has the .pth file.
> > 
> > 
> > you could change the extension from .pth to .pkl, there is no big difference, only different ways when saving data.
> 
> ps: change the extension in the code.

Hi, thanks for you rapid reply
well, I try to append the args --output, and  annotation the  241 line of test.py assert False.
but there is error, which is
```
writing results to pkl/test.pkl
Traceback (most recent call last):
  File "./tools/test.py", line 263, in <module>
    main()
  File "./tools/test.py", line 242, in main
    mmcv.dump(outputs['bbox_results'], args.out)
TypeError: list indices must be integers or slices, not str
```

**Comment by cc1oud** [comment]
> > > > Hi， I want to know how to save the output as .pkl file, I only has the .pth file.
> > > 
> > > 
> > > you could change the extension from .pth to .pkl, there is no big difference, only different ways when saving data.
> > 
> > 
> > ps: change the extension in the code.
> 
> Hi, thanks for you rapid reply well, I try to append the args --output, and annotation the 241 line of test.py assert False. but there is error, which is
> 
> ```
> writing results to pkl/test.pkl
> Traceback (most recent call last):
>   File "./tools/test.py", line 263, in <module>
>     main()
>   File "./tools/test.py", line 242, in main
>     mmcv.dump(outputs['bbox_results'], args.out)
> TypeError: list indices must be integers or slices, not str
> ```
OK，i change the `mmcv.dump(outputs['bbox_results'], args.out)` -> `mmcv.dump(outputs, args.out)`
and get the .pkl file about 20.5 GB

**Comment by Unusual6** [comment]
> > Hi， I want to know how to save the output as .pkl file, I only has the .pth file.
> 
> you could change the extension from .pth to .pkl, there is no big difference, only different ways when saving data.

Hi , I think that .pth is the weigths of model checkpoints and .pkl is a output file of model . Can you explain why  there is no big difference?

**Comment by yux-lab** [comment]
Hi, do you know how to solve the issue of stage-2 accuracy being 0? Is it necessary to make modifications at a specific location?
![Uploading 20241128165036.jpg…]()

**Comment by qianlongwuyong11** [comment]
欧克
